# Generated by Django 4.2.3 on 2023-09-08 11:29

from django.db import migrations, models
import parentsdataform.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('aadhar_number', models.CharField(max_length=150)),
                ('pan_number', models.CharField(max_length=150)),
                ('has_disability', models.BooleanField(default=False)),
                ('pension_eligible', models.BooleanField(default=False)),
                ('pension_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mobile_number', models.CharField(max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, help_text='Do not Enter Age Field as its caluculated automatically', null=True)),
                ('address', models.CharField(default='Unknown', max_length=500)),
                ('remarks', models.CharField(blank=True, help_text='Add remarks about the student', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to=parentsdataform.models.student_image_path, validators=[parentsdataform.models.validate_image_extension, parentsdataform.models.validate_image_size])),
            ],
        ),
    ]
