# Generated by Django 4.2.3 on 2023-09-09 10:35

from django.db import migrations, models
import parentsdataform.models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsdataform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='image',
            field=models.ImageField(blank=True, default='No image Availbe', null=True, upload_to=parentsdataform.models.student_image_path, validators=[parentsdataform.models.validate_image_extension, parentsdataform.models.validate_image_size]),
        ),
    ]
