# Generated by Django 4.1.7 on 2023-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=50)),
                ('student_aadhar', models.CharField(max_length=50)),
                ('father_aadhar', models.CharField(max_length=50)),
                ('mother_aadhar', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
