# Generated by Django 4.1.7 on 2023-03-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdataform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_aadhar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_aadhar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_aadhar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=150),
        ),
    ]
