# Generated by Django 4.1.7 on 2023-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdataform', '0002_alter_student_father_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
