# Generated by Django 4.1.7 on 2023-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdataform', '0003_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, default='Leve this Field Empty', null=True),
        ),
    ]
