# Generated by Django 4.1.7 on 2023-03-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdataform', '0005_student_image_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
