# Generated by Django 4.2.3 on 2023-08-30 09:15

import django.core.validators
from django.db import migrations, models
import studentsdataform.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdataform', '0009_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only JPG, JPEG, and PNG images are allowed.'), studentsdataform.models.validate_image_extension, studentsdataform.models.validate_image_size]),
        ),
    ]
