# Generated by Django 4.2.3 on 2023-08-30 09:17

from django.db import migrations, models
import studentsdataform.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdataform', '0010_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/', validators=[studentsdataform.models.validate_image_extension, studentsdataform.models.validate_image_size]),
        ),
    ]
