# Generated by Django 4.2.3 on 2023-09-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdataform', '0013_student_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, help_text='Do not Enter Age Field as its caluculated automatically', null=True),
        ),
    ]
